### ISSUE TITLE
TypeError: setup.device is not a function

### ISSUE THREAD

**Issue by Vasya-Zo** [dojot/mqtt-emulator#2]
Hello! I have a problem using Emulator in Node-Red

8/6/2018, 6:45:06AM 
node: Emulator
msg : error
"TypeError: setup.device is not a function"

how can i fix it?

**Comment by giovannicuriel** [comment]
Hi! 
There's a quick workaround for this: in emulator.js file, change the code to look like this:

```javascript
const { setup, device, eventInterval } = require('../app/setup');
const generate = require('../app/generate');
const ganerateUtils = require('../app/generate/utils');
const scheduler = require('../app/scheduler');
const utils = require('../app/utils');

run = (node, config) => {

    node.status({ fill: "blue", shape: "dot", text: "emulating" });
    device(config)
        .then(eventInterval)
        .then(generate)
        .then(sensors => {
....

```

Differences are: we are importing now `device` from `../app/setup` and using it instead of `setup.device`


Let me know if this worked.

**Comment by Vasya-Zo** [comment]
It works now. Thank you!
